#!/usr/bin/env python3
"""
═══════════════════════════════════════════════════════════════════
What The Bug — Integrated Verification Dev Server & Simulation Hub
═══════════════════════════════════════════════════════════════════
Provides:
  - Static HTTP file serving (What The Bug platform + UVMCourse Digital Book & Labs)
  - POST /api/simulate (and /simulate): Dual-engine native execution:
      * Verilator 5.050 (native C++ binary compilation & simulation with UVM 1.2)
      * Xezim (high-speed instant SystemVerilog & UVM 1.2 simulation)
  - POST /api/lint (and /lint): Fast syntax & lint checking
  - GET  /api/status: Real-time simulator engine availability & path detection
"""

import http.server
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import uuid

PORT = 8000
WORKSPACE_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Dynamic Tool Path Discovery ──────────────────────────────────
def find_xezim():
    candidates = [
        os.environ.get("XEZIM_BIN"),
        shutil.which("xezim"),
        os.path.expanduser("~/.cargo/bin/xezim"),
        "/Users/mac/xezim-workspace/xezim/target/release/xezim",
        "/usr/local/bin/xezim"
    ]
    for c in candidates:
        if c and os.path.isfile(c) and os.access(c, os.X_OK):
            return os.path.abspath(c)
    return "/Users/mac/xezim-workspace/xezim/target/release/xezim"

def find_verilator():
    candidates = [
        os.environ.get("VERILATOR_BIN"),
        shutil.which("verilator"),
        "/usr/local/bin/verilator",
        "/opt/homebrew/bin/verilator"
    ]
    for c in candidates:
        if c and os.path.isfile(c) and os.access(c, os.X_OK):
            return os.path.abspath(c)
    return shutil.which("verilator") or "/usr/local/bin/verilator"

def find_uvm_src():
    candidates = [
        os.environ.get("UVM_12_SRC"),
        os.environ.get("UVM_SRC"),
        os.path.expanduser("~/xezim-workspace/uvm-1.2/src"),
        "/Users/mac/xezim-workspace/uvm-1.2/src",
        "/usr/local/share/uvm-1.2/src",
        "/uvm/uvm-1.2/src"
    ]
    for c in candidates:
        if c and os.path.isdir(c):
            return os.path.abspath(c)
    return "/Users/mac/xezim-workspace/uvm-1.2/src"

def find_base_obj_dir():
    candidates = [
        "/Users/mac/Documents/INTERVIEW/UVMCourse/obj_dir",
        os.path.join(WORKSPACE_DIR, "uvm_course", "obj_dir"),
        os.path.join(WORKSPACE_DIR, "obj_dir")
    ]
    for c in candidates:
        if c and os.path.isdir(c) and os.path.isfile(os.path.join(c, "Vtop__ALL.a")):
            return os.path.abspath(c)
    for c in candidates:
        if c and os.path.isdir(c):
            return os.path.abspath(c)
    return None

XEZIM_BIN     = find_xezim()
VERILATOR_BIN = find_verilator()
UVM_SRC       = find_uvm_src()
BASE_OBJ_DIR  = find_base_obj_dir()

ALLOWED_BINARIES = {"xezim", "verilator", os.path.basename(XEZIM_BIN), "vvp", "iverilog"}
DANGEROUS_CHARS  = re.compile(r'[;&|`><*\?\[\]\{\}\(\)\!\#\~]')

# ── Code Analysis Helpers ─────────────────────────────────────────
def strip_sv_comments(code: str) -> str:
    if not code:
        return ""
    code = re.sub(r'/\*[\s\S]*?\*/', '', code)
    code = re.sub(r'//.*$', '', code, flags=re.MULTILINE)
    return code

def extract_modules(code: str) -> list:
    clean = strip_sv_comments(code)
    clean = re.sub(r'"(\\.|[^"\\])*"', '""', clean)
    matches = re.findall(r'\bmodule\s+([a-zA-Z0-9_]+)\s*(\(|#|;)', clean)
    return [m[0] for m in matches if m[0] != "uvm_pkg"]

def extract_interfaces(code: str) -> list:
    clean = strip_sv_comments(code)
    clean = re.sub(r'"(\\.|[^"\\])*"', '""', clean)
    matches = re.findall(r'(?<!\bvirtual\s)\binterface\s+([a-zA-Z0-9_]+)\s*(\(|#|;)', clean)
    return [m[0] for m in matches]

def extract_packages(code: str) -> list:
    clean = strip_sv_comments(code)
    clean = re.sub(r'"(\\.|[^"\\])*"', '""', clean)
    matches = re.findall(r'\bpackage\s+([a-zA-Z0-9_]+)\s*;', clean)
    return [m for m in matches if m != "uvm_pkg"]

def convert_xtrace_to_standard_vcd(xtrace_text: str) -> str:
    lines = xtrace_text.splitlines()
    sym_map = {}
    time = 0
    out = [
        '$date\n  Generated by xezim converter\n$end',
        '$version\n  xezim 0.1\n$end',
        '$timescale\n  1ns\n$end',
        '$scope module top $end'
    ]
    in_dict = False
    in_trace = False
    sym_code = 33

    for line in lines:
        line = line.strip()
        if line == '@section dict':
            in_dict = True
            continue
        elif line == '@section trace':
            in_dict = False
            in_trace = True
            out.append('$enddefinitions $end')
            out.append('#0')
            out.append('$dumpvars')
            continue

        if in_dict and line.startswith('S,'):
            parts = line.split(',')
            sig_id   = parts[1]
            sig_name = parts[3]
            sig_type = parts[4] if len(parts) > 4 else 'bit'
            width = 1
            if sig_type == 'u8':   width = 8
            elif sig_type == 'u16': width = 16
            elif sig_type == 'u32': width = 32
            elif sig_type == 'u64': width = 64

            while sym_code in (34, 39, 92):
                sym_code += 1
            sym = chr(sym_code)
            sym_code += 1
            sym_map[sig_id] = (sig_name, width, sym)
            out.append(f'$var wire {width} {sym} {sig_name} $end')

        elif in_trace:
            if line.startswith('T,'):
                t_str = line.split(',')[1]
                if t_str.startswith('+'):
                    time += int(t_str[1:])
                else:
                    time = int(t_str)
                out.append(f'#{time}')
            elif line.startswith('P,') or line.startswith('N,full,') or line.startswith('D,'):
                parts = line.split(',')
                items = parts[1:]
                for item in items:
                    if '=' in item:
                        k, v = item.split('=', 1)
                        if k in sym_map:
                            s_name, width, sym = sym_map[k]
                            val_str = v.replace('0x', '').replace('0b', '')
                            if width == 1:
                                bit_val = '1' if '1' in val_str else '0'
                                out.append(f'{bit_val}{sym}')
                            else:
                                try:
                                    num = int(val_str, 16) if '0x' in v else (int(val_str, 2) if '0b' in v else int(val_str))
                                    b_val = format(num, f'0{width}b')
                                except Exception:
                                    b_val = '0' * width
                                out.append(f'b{b_val} {sym}')

    out.append('$end')
    return '\n'.join(out)


# ── HTTP Request Handler ──────────────────────────────────────────
class DevServerHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=WORKSPACE_DIR, **kwargs)

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.end_headers()

    def do_GET(self):
        if self.path == "/api/status":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()

            xezim_ok = os.path.isfile(XEZIM_BIN) and os.access(XEZIM_BIN, os.X_OK)
            verilator_ok = os.path.isfile(VERILATOR_BIN) and os.access(VERILATOR_BIN, os.X_OK)
            uvm_ok = os.path.isdir(UVM_SRC)

            status = {
                "status": "online",
                "xezim_available": xezim_ok,
                "xezim_path": XEZIM_BIN,
                "verilator_available": verilator_ok,
                "verilator_path": VERILATOR_BIN,
                "uvm_available": uvm_ok,
                "uvm_path": UVM_SRC,
                "uvm_src": UVM_SRC,
                "base_obj_dir": BASE_OBJ_DIR,
                "verilator": {
                    "available": verilator_ok,
                    "path": VERILATOR_BIN,
                    "version": "5.050 (Homebrew)"
                },
                "xezim": {
                    "available": xezim_ok,
                    "path": XEZIM_BIN,
                    "version": "0.1.0"
                },
                "server_time": time.time(),
                "port": PORT
            }
            self.wfile.write(json.dumps(status, indent=2).encode("utf-8"))
            return

        super().do_GET()

    def do_POST(self):
        if self.path in ("/api/simulate", "/simulate"):
            self.handle_simulate()
        elif self.path in ("/api/lint", "/lint"):
            self.handle_lint()
        else:
            self.send_error(404, f"API endpoint {self.path} not found")

    def handle_simulate(self):
        content_len = int(self.headers.get("Content-Length", 0))
        post_body = self.rfile.read(content_len)
        try:
            req = json.loads(post_body.decode("utf-8"))
        except Exception as e:
            self.send_json_error(400, f"Invalid JSON payload: {e}")
            return

        # ── 1. Normalize Files Input ──
        # Supports:
        # A) dict: { "top.sv": "content...", "test.sv": "content..." } (UVMCourse digital_book)
        # B) list: [ {"name": "top.sv", "content": "..."}, ... ] (Custom Playground)
        # C) code string: { "code": "module top..." } (CompilerBridge /lint)
        files_dict = {}
        raw_files = req.get("files")
        if isinstance(raw_files, dict):
            files_dict = raw_files
        elif isinstance(raw_files, list):
            for i, f in enumerate(raw_files):
                name = f.get("name", f"source_{i}.sv")
                files_dict[name] = f.get("content", "")
        elif "code" in req:
            files_dict["scratch.sv"] = req["code"]

        if not files_dict:
            self.send_json_error(400, "No files provided for simulation")
            return

        engine      = req.get("engine", "verilator").lower()
        top_module  = req.get("top", "top")
        is_sv       = req.get("is_sv", False)
        active_file = req.get("active_file", "")
        custom_cmd  = req.get("command", "")

        plusargs = req.get("plusargs", [])
        if isinstance(plusargs, str):
            plusargs = [p.strip() for p in plusargs.split() if p.strip()]

        tmp_dir = tempfile.mkdtemp(prefix="wtb_sim_")
        t0 = time.time()
        try:
            # ── 2. Pre-seed obj_dir from cache if available (macOS APFS instant clone) ──
            if engine == "verilator" and BASE_OBJ_DIR and os.path.isdir(BASE_OBJ_DIR):
                try:
                    subprocess.run(["cp", "-cR", BASE_OBJ_DIR, os.path.join(tmp_dir, "obj_dir")], check=False)
                except Exception:
                    pass

            # ── 3. Write All Source Files to Temporary Directory ──
            file_paths = []
            subdirs = set()
            for fname in files_dict.keys():
                dirname = os.path.dirname(fname)
                if dirname:
                    subdirs.add(dirname)

            for fname, fcontent in files_dict.items():
                base_name = os.path.basename(fname)
                if not fcontent.endswith("\n"):
                    fcontent += "\n"

                # Write to root of tmp_dir
                root_target = os.path.join(tmp_dir, base_name)
                with open(root_target, "w", encoding="utf-8") as fp:
                    fp.write(fcontent)

                # Write preserving relative directory hierarchy
                rel_target = os.path.join(tmp_dir, fname)
                os.makedirs(os.path.dirname(rel_target), exist_ok=True)
                with open(rel_target, "w", encoding="utf-8") as fp:
                    fp.write(fcontent)

                # Write to subdirectories for include resolution
                for sd in subdirs:
                    sd_p = os.path.join(tmp_dir, sd, base_name)
                    os.makedirs(os.path.dirname(sd_p), exist_ok=True)
                    with open(sd_p, "w", encoding="utf-8") as fp:
                        fp.write(fcontent)

                # Extra include aliases for .pkg and .incl extensions
                if base_name.endswith(".pkg") or base_name.endswith(".incl"):
                    alias_root = os.path.join(tmp_dir, base_name + ".sv")
                    with open(alias_root, "w", encoding="utf-8") as fp:
                        fp.write(fcontent)

                if fname.endswith(".sv") or fname.endswith(".v"):
                    file_paths.append(fname)

            # ── 4. Detect Includes & Filter Compilation Units ──
            included_files = set()
            for fname, fcontent in files_dict.items():
                clean_code = strip_sv_comments(fcontent)
                for inc in re.findall(r'`include\s+["<]([^">]+)[">]', clean_code):
                    included_files.add(os.path.basename(inc))

            compilation_files = [f for f in file_paths if os.path.basename(f) not in included_files]

            # Module / interface filtering
            module_comp_files = []
            for cf in compilation_files:
                code = files_dict.get(cf, "")
                clean = strip_sv_comments(code)
                if re.search(r'\b(module|interface|program)\s+[a-zA-Z0-9_]+', clean):
                    module_comp_files.append(cf)

            if module_comp_files:
                compilation_files = module_comp_files

            if active_file and active_file in files_dict and os.path.basename(active_file) not in included_files and active_file not in compilation_files:
                compilation_files.append(active_file)

            if not compilation_files:
                compilation_files = file_paths

            # ── 5. Auto-Detect Top Module ──
            modules_found = []
            for fname, fcontent in files_dict.items():
                for m in extract_modules(fcontent):
                    if m not in modules_found:
                        modules_found.append(m)

            active_mods = extract_modules(files_dict.get(active_file, ""))
            top_candidates = [m for m in modules_found if m in ["tb", "top", "testbench", "tb_top", "wb_conmax_tb_top", "wb_env_top_mod"] or m.endswith(("_tb", "_top", "_top_mod"))]

            if top_module in modules_found:
                top = top_module
            elif top_candidates:
                top = top_candidates[0]
            elif "top" in active_mods:
                top = "top"
            elif active_mods:
                top = active_mods[-1]
            elif modules_found:
                top = modules_found[-1]
            else:
                top = "top"
                auto_top_file = "_sim_top.sv"
                auto_top_code = (
                    "`timescale 1ns/1ps\n"
                    "`include \"uvm_macros.svh\"\n"
                    "module top;\n"
                    "  import uvm_pkg::*;\n"
                    "  initial begin\n"
                    "    `uvm_info(\"UVM_TOP\", \"UVM verification environment loaded successfully.\", UVM_LOW)\n"
                    "    $display(\"Simulation finished successfully.\");\n"
                    "    $finish;\n"
                    "  end\n"
                    "endmodule\n"
                )
                with open(os.path.join(tmp_dir, auto_top_file), "w", encoding="utf-8") as fp:
                    fp.write(auto_top_code)
                compilation_files.append(auto_top_file)

            # Auto-inject +UVM_TESTNAME if needed
            if not any("UVM_TESTNAME" in p for p in plusargs):
                for fname, fcontent in files_dict.items():
                    clean_content = strip_sv_comments(fcontent)
                    test_classes = re.findall(r'\bclass\s+([a-zA-Z0-9_]+)\s+extends\s+uvm_test\b', clean_content)
                    if test_classes:
                        plusargs.append(f"+UVM_TESTNAME={test_classes[-1]}")
                        break

            # ── 6. Setup Include Directory Flags ──
            abs_run_dir = os.path.abspath(tmp_dir)
            inc_flags = ["-I.", f"-I{abs_run_dir}"]
            if not is_sv and os.path.isdir(UVM_SRC):
                inc_flags.append(f"-I{UVM_SRC}")
            for sd in subdirs:
                inc_flags.append(f"-I{os.path.join(abs_run_dir, sd)}")
            inc_flags = list(dict.fromkeys(inc_flags))

            # ── 7. Execute Simulation by Engine ──
            uvm_pkg = os.path.join(UVM_SRC, "uvm_pkg.sv")
            uses_uvm = (not is_sv) and os.path.isdir(UVM_SRC)

            stdout = ""
            stderr = ""
            compile_stdout = ""
            compile_stderr = ""
            exit_code = 0
            compile_time_ms = 0
            sim_time_ms = 0

            if engine == "verilator":
                # Verilator Compilation Command
                warn_flags = [
                    "-Wno-fatal", "-Wno-WIDTH", "-Wno-STMTDLY", "-Wno-IMPLICIT",
                    "-Wno-MODDUP", "-Wno-PINMISSING", "-Wno-CASEINCOMPLETE",
                    "-Wno-TIMESCALEMOD", "-Wno-CASTCONST", "-Wno-IMPLICITSTATIC",
                    "-Wno-DECLFILENAME", "-Wno-EOFNEWLINE", "-Wno-COVERIGN",
                    "+libext+.pkg+.sv+.svh+.v+.incl"
                ]
                if uses_uvm:
                    uvm_defs = ["+define+UVM_NO_DPI"]
                    cmd_compile = [VERILATOR_BIN, "--binary", "--timing"] + warn_flags + uvm_defs + inc_flags + [uvm_pkg] + compilation_files + ["--top-module", top, "-j", "4"]
                else:
                    cmd_compile = [VERILATOR_BIN, "--binary", "--timing"] + warn_flags + inc_flags + compilation_files + ["--top-module", top, "-j", "4"]

                t_compile_start = time.time()
                compile_proc = subprocess.run(
                    cmd_compile,
                    cwd=tmp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=120
                )
                compile_time_ms = int((time.time() - t_compile_start) * 1000)
                compile_stdout = compile_proc.stdout or ""
                compile_stderr = compile_proc.stderr or ""
                exit_code = compile_proc.returncode

                if exit_code != 0:
                    resp = {
                        "success": False,
                        "exit_code": exit_code,
                        "stdout": compile_stdout,
                        "stderr": compile_stderr,
                        "compile_stdout": compile_stdout,
                        "compile_stderr": compile_stderr,
                        "command": " ".join(cmd_compile),
                        "compile_time_ms": compile_time_ms,
                        "sim_time_ms": 0,
                        "total_time_ms": compile_time_ms,
                        "engine": "verilator",
                        "error": "Verilator compilation failed. See compiler output for errors."
                    }
                    self.send_json_response(resp)
                    return

                # Find the compiled binary
                binary_path = os.path.join(tmp_dir, "obj_dir", f"V{top}")
                if not os.path.exists(binary_path):
                    obj_dir_path = os.path.join(tmp_dir, "obj_dir")
                    if os.path.isdir(obj_dir_path):
                        for f in os.listdir(obj_dir_path):
                            cand = os.path.join(obj_dir_path, f)
                            if os.access(cand, os.X_OK) and not f.endswith((".o", ".a", ".d")):
                                binary_path = cand
                                break

                # Run simulation binary
                t_sim_start = time.time()
                sim_cmd = [binary_path] + plusargs
                sim_proc = subprocess.run(
                    sim_cmd,
                    cwd=tmp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=30
                )
                sim_time_ms = int((time.time() - t_sim_start) * 1000)
                stdout = sim_proc.stdout or ""
                stderr = sim_proc.stderr or ""
                exit_code = sim_proc.returncode

            else:
                # Engine: XEZIM
                xezim_inc = [f"-I{UVM_SRC}"] if uses_uvm else []
                xezim_inc.extend(inc_flags)
                if uses_uvm:
                    cmd_sim = [XEZIM_BIN] + xezim_inc + [uvm_pkg] + compilation_files + plusargs
                else:
                    cmd_sim = [XEZIM_BIN] + xezim_inc + compilation_files + plusargs

                t_sim_start = time.time()
                sim_proc = subprocess.run(
                    cmd_sim,
                    cwd=tmp_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=35
                )
                sim_time_ms = int((time.time() - t_sim_start) * 1000)
                stdout = sim_proc.stdout or ""
                stderr = sim_proc.stderr or ""
                exit_code = sim_proc.returncode

            # ── 8. Collect Waveforms & Coverage ──
            vcd_content = None
            vcd_found_name = None
            for root, _, fnames in os.walk(tmp_dir):
                for fn in fnames:
                    if fn.endswith(".vcd") or fn.endswith(".fst"):
                        vcd_found_name = fn
                        fpath = os.path.join(root, fn)
                        if os.path.getsize(fpath) < 25 * 1024 * 1024:
                            try:
                                with open(fpath, "r", encoding="utf-8", errors="replace") as vfp:
                                    raw = vfp.read()
                                if raw.startswith("@xtrace"):
                                    vcd_content = convert_xtrace_to_standard_vcd(raw)
                                else:
                                    vcd_content = raw
                            except Exception:
                                pass
                        break
                if vcd_content:
                    break

            cov_data = None
            cov_path = os.path.join(tmp_dir, "xezim_cov.json")
            if os.path.exists(cov_path):
                try:
                    with open(cov_path, "r") as cf:
                        cov_data = json.load(cf)
                except Exception:
                    pass

            total_elapsed_ms = int((time.time() - t0) * 1000)

            resp = {
                "success": exit_code == 0,
                "exit_code": exit_code,
                "stdout": stdout,
                "stderr": stderr,
                "compile_stdout": compile_stdout,
                "compile_stderr": compile_stderr,
                "engine": engine,
                "compile_time_ms": compile_time_ms,
                "sim_time_ms": sim_time_ms,
                "total_time_ms": total_elapsed_ms,
                "elapsed_ms": total_elapsed_ms,
                "waveform": vcd_found_name,
                "has_vcd": vcd_content is not None,
                "vcd": vcd_content,
                "vcd_text": vcd_content,
                "coverage": cov_data
            }
            self.send_json_response(resp)

        except subprocess.TimeoutExpired:
            self.send_json_error(504, f"Simulation timed out (> 60s). Check for infinite loops in testbench.")
        except Exception as ex:
            self.send_json_error(500, f"Execution failed: {str(ex)}")
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    def handle_lint(self):
        content_len = int(self.headers.get("Content-Length", 0))
        post_body = self.rfile.read(content_len)
        try:
            req = json.loads(post_body.decode("utf-8"))
        except Exception as e:
            self.send_json_error(400, f"Invalid JSON payload: {e}")
            return

        code = req.get("code", "")
        if not code and "files" in req:
            files = req["files"]
            if isinstance(files, dict):
                code = "\n".join(files.values())
            elif isinstance(files, list):
                code = "\n".join(f.get("content", "") for f in files)

        tmp_dir = tempfile.mkdtemp(prefix="wtb_lint_")
        try:
            src_path = os.path.join(tmp_dir, "scratch.sv")
            if not code.endswith("\n"):
                code += "\n"
            with open(src_path, "w", encoding="utf-8") as fp:
                fp.write(code)

            cmd = [
                VERILATOR_BIN,
                "--lint-only",
                "-Wall",
                "-Wno-fatal",
                "-Wno-DECLFILENAME",
                "-Wno-EOFNEWLINE",
                "--timing"
            ]
            if ("uvm_pkg" in code or "uvm_component" in code) and os.path.isdir(UVM_SRC):
                cmd.extend([
                    "+define+UVM_NO_DPI",
                    f"-I{UVM_SRC}",
                    os.path.join(UVM_SRC, "uvm_pkg.sv")
                ])
            cmd.append(src_path)

            proc = subprocess.run(
                cmd,
                cwd=tmp_dir,
                capture_output=True,
                text=True,
                timeout=20
            )
            output = (proc.stdout + "\n" + proc.stderr).strip()
            self.send_json_response({
                "success": proc.returncode == 0,
                "exit_code": proc.returncode,
                "output": output,
                "stdout": proc.stdout,
                "stderr": proc.stderr
            })
        except Exception as ex:
            self.send_json_error(500, f"Lint failed: {str(ex)}")
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    def send_json_response(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def send_json_error(self, code, message):
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps({"success": False, "error": message}).encode("utf-8"))


def main():
    port = PORT
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            pass

    server_address = ("", port)
    httpd = http.server.HTTPServer(server_address, DevServerHandler)
    print(f"═══════════════════════════════════════════════════════════════════")
    print(f"⚡ WHAT THE BUG — DV Simulation Hub Online")
    print(f"   URL:            http://localhost:{port}/")
    print(f"   UVM Course:     http://localhost:{port}/uvm_course/index.html")
    print(f"   Course Catalog: http://localhost:{port}/uvm_course/home.html")
    print(f"   Verilator:      {VERILATOR_BIN}")
    print(f"   Xezim:          {XEZIM_BIN}")
    print(f"   UVM 1.2 SRC:    {UVM_SRC}")
    if BASE_OBJ_DIR:
        print(f"   obj_dir Cache:  {BASE_OBJ_DIR} (APFS Instant Fast-Path)")
    print(f"═══════════════════════════════════════════════════════════════════")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down server.")
        httpd.server_close()

if __name__ == "__main__":
    main()
