"""
═══════════════════════════════════════════════════════════════════
WTB Simulation Server — whathebug.com
FastAPI port of compile_server.py

Supports:
  - xezim  (primary: SV, UVM 1.2, UVM 2020)
  - verilator (fallback: lint only)
  - VCD / XTrace waveform output
  - Coverage JSON (xezim_cov.json)
  - Rate limiting: 10 req/min per IP
  - CORS: open (public educational tool)
  - Isolated temp dirs per request
═══════════════════════════════════════════════════════════════════
"""

import os
import json
import subprocess
import tempfile
import shutil
import re
import time as time_module

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

# ── Rate Limiter ────────────────────────────────────────────────
limiter = Limiter(key_func=get_remote_address)

app = FastAPI(
    title="WTB Simulation Server",
    description="xezim + Verilator simulation backend for whathebug.com",
    version="1.0.0"
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# ── CORS ─────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)

# ── Paths ────────────────────────────────────────────────────────
XEZIM_BIN    = os.environ.get("XEZIM_BIN", "/usr/local/bin/xezim")
UVM_12_SRC   = os.environ.get("UVM_12_SRC", "/uvm/uvm-1.2/src")
UVM_2020_SRC = os.environ.get("UVM_2020_SRC", "/uvm/uvm-2020/src")

# ── Request Schema ───────────────────────────────────────────────
class SimRequest(BaseModel):
    code: str
    command: str = f"{XEZIM_BIN} --parse $FILE"


# ── XTrace → Standard VCD Converter ─────────────────────────────
# Ported verbatim from compile_server.py — converts xezim's
# compact XTrace format to standard IEEE VCD for the waveform viewer.
def convert_xtrace_to_standard_vcd(xtrace_text: str) -> str:
    lines = xtrace_text.splitlines()
    sym_map = {}
    time = 0

    out = [
        '$date\n  Generated by xezim converter\n$end',
        '$version\n  xezim 0.1\n$end',
        '$timescale\n  1ns\n$end',
        '$scope module top $end'
    ]

    in_dict = False
    in_trace = False
    sym_code = 33  # ASCII '!'

    for line in lines:
        line = line.strip()
        if line == '@section dict':
            in_dict = True
            continue
        elif line == '@section trace':
            in_dict = False
            in_trace = True
            out.append('$enddefinitions $end')
            out.append('#0')
            out.append('$dumpvars')
            continue

        if in_dict and line.startswith('S,'):
            parts = line.split(',')
            sig_id   = parts[1]
            sig_name = parts[3]
            sig_type = parts[4] if len(parts) > 4 else 'bit'
            width = 1
            if sig_type == 'u8':   width = 8
            elif sig_type == 'u16': width = 16
            elif sig_type == 'u32': width = 32
            elif sig_type == 'u64': width = 64

            while sym_code in (34, 39, 92):
                sym_code += 1
            sym = chr(sym_code)
            sym_code += 1
            sym_map[sig_id] = (sig_name, width, sym)
            out.append(f'$var wire {width} {sym} {sig_name} $end')

        elif in_trace:
            if line.startswith('T,'):
                t_str = line.split(',')[1]
                if t_str.startswith('+'):
                    time += int(t_str[1:])
                else:
                    time = int(t_str)
                out.append(f'#{time}')
            elif line.startswith('P,') or line.startswith('N,full,') or line.startswith('D,'):
                parts = line.split(',')
                items = parts[1:]
                for item in items:
                    if '=' in item:
                        k, v = item.split('=', 1)
                        if k in sym_map:
                            s_name, width, sym = sym_map[k]
                            val_str = v.replace('0x', '').replace('0b', '')
                            if width == 1:
                                bit_val = '1' if '1' in val_str else '0'
                                out.append(f'{bit_val}{sym}')
                            else:
                                try:
                                    num = int(val_str, 16) if '0x' in v else (int(val_str, 2) if '0b' in v else int(val_str))
                                    b_val = format(num, f'0{width}b')
                                except Exception:
                                    b_val = '0' * width
                                out.append(f'b{b_val} {sym}')
                    elif len(parts) >= 3 and parts[0] == 'D':
                        k = parts[1]
                        v = parts[2]
                        if k in sym_map:
                            s_name, width, sym = sym_map[k]
                            if width == 1:
                                bit_val = '1' if '1' in v else '0'
                                out.append(f'{bit_val}{sym}')
                            else:
                                try:
                                    num = int(v, 16) if '0x' in v else (int(v, 2) if '0b' in v else int(v))
                                    b_val = format(num, f'0{width}b')
                                except Exception:
                                    b_val = '0' * width
                                out.append(f'b{b_val} {sym}')

    out.append('$end')
    return '\n'.join(out)


# ── Health Endpoint ──────────────────────────────────────────────
@app.get("/health")
def health():
    return {
        "status": "ok",
        "xezim": os.path.exists(XEZIM_BIN),
        "xezim_path": XEZIM_BIN,
        "uvm_1_2": os.path.exists(UVM_12_SRC),
        "uvm_2020": os.path.exists(UVM_2020_SRC),
    }


# ── Main Simulation Endpoint ─────────────────────────────────────
@app.post("/lint")
@limiter.limit("10/minute")
async def lint(request: Request, body: SimRequest):
    code    = body.code
    command = body.command

    # Resolve cloud xezim path if command still carries Mac-local paths
    command = command.replace(
        '/Users/mac/xezim-workspace/xezim/target/release/xezim', XEZIM_BIN
    ).replace(
        '/Users/mac/xezim-workspace/uvm-1.2/src', UVM_12_SRC
    )

    tmp_dir = tempfile.mkdtemp(prefix="wtb_sim_")
    try:
        return await _run_simulation(code, command, tmp_dir)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


async def _run_simulation(code: str, command: str, tmp_dir: str):
    temp_filename = os.path.join(tmp_dir, 'scratch.sv')
    vcd_filename  = 'wave.vcd'

    # ── Auto-detect VCD filename from user code ──────────────────
    match = re.search(r'\$dumpfile\s*\(\s*["\']([^"\']+)["\']\s*\)', code)
    if match:
        vcd_filename = match.group(1)
    elif 'endmodule' in code and '--simulate' in command:
        dump_code = '\ninitial begin\n  $dumpfile("wave.vcd");\n  $dumpvars(0);\nend\n'
        parts = code.rsplit('endmodule', 1)
        code = parts[0] + dump_code + 'endmodule' + parts[1]
        vcd_filename = 'wave.vcd'

    # ── Write SV source ──────────────────────────────────────────
    # Ensure source ends with a newline to satisfy POSIX/Verilator
    if not code.endswith('\n'):
        code += '\n'
        
    with open(temp_filename, 'w') as f:
        f.write(code)

    # ── Parse and Sanitize command safely (no shell=True) ────────
    # Split the raw command line into distinct arguments
    import shlex
    raw_args = shlex.split(command)
    if not raw_args:
        return JSONResponse(status_code=400, content={'error': 'Empty command payload', 'success': False})

    # Strict whitelist validation to block malicious shells, paths, or injection characters
    allowed_binaries = {'xezim', 'verilator', XEZIM_BIN, 'vvp', 'iverilog'}
    binary_invoked = os.path.basename(raw_args[0])
    if binary_invoked not in allowed_binaries:
        return JSONResponse(status_code=400, content={
            'error': f'Disallowed execution target: {binary_invoked}',
            'success': False
        })

    # Resolve executable path
    cmd_args = []
    if binary_invoked == 'xezim':
        cmd_args.append(XEZIM_BIN)
    else:
        cmd_args.append(raw_args[0])

    # Validate remaining arguments against shell metacharacters (allow $ for $FILE variable placeholder)
    dangerous_chars = re.compile(r'[;&|`><*\?\[\]\{\}\(\)\!\#\~]')
    for arg in raw_args[1:]:
        # Remove local workspace prefix mappings dynamically if present
        if '/Users/mac/xezim-workspace/uvm-1.2/src' in arg:
            arg = arg.replace('/Users/mac/xezim-workspace/uvm-1.2/src', UVM_12_SRC)
        
        # Guard against injection tokens or directory traversal attempts
        if dangerous_chars.search(arg) or '..' in arg:
            return JSONResponse(status_code=400, content={
                'error': f'Forbidden characters or paths detected in arguments: {arg}',
                'success': False
            })
        
        if arg == '$FILE':
            cmd_args.append(temp_filename)
        else:
            cmd_args.append(arg)

    # Ensure $FILE is appended if not explicitly present in inputs
    if temp_filename not in cmd_args:
        cmd_args.append(temp_filename)

    # Automatically add Warning suppression flag sets for Verilator runs
    if 'verilator' in binary_invoked:
        if '-Wno-DECLFILENAME' not in cmd_args:
            cmd_args.append('-Wno-DECLFILENAME')
        if '-Wno-EOFNEWLINE' not in cmd_args:
            cmd_args.append('-Wno-EOFNEWLINE')

    # Automatically add XTrace dumping configs for xezim runs
    if 'xezim' in binary_invoked and '--simulate' in cmd_args and '--xtrace' not in cmd_args:
        cmd_args.extend(['--xtrace', os.path.join(tmp_dir, 'wave.vcd')])

    print(f"[WTB] Executing structured command: {cmd_args}")

    # ── Safe Execution without shell=True ────────────────────────
    try:
        result = subprocess.run(
            cmd_args,
            cwd=tmp_dir,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=120
        )
    except subprocess.TimeoutExpired:
        return JSONResponse(status_code=200, content={
            'exit_code': -1,
            'stdout': '',
            'stderr': '[TIMEOUT] Simulation exceeded 120s limit. Try a shorter simulation or reduce $finish time.',
            'success': False
        })

    # ── Collect VCD output ───────────────────────────────────────
    vcd_text_str = None
    for fname in os.listdir(tmp_dir):
        if fname.endswith('.vcd'):
            fpath = os.path.join(tmp_dir, fname)
            if os.path.getsize(fpath) < 50 * 1024 * 1024:  # skip >50MB
                try:
                    with open(fpath, 'r', errors='ignore') as vf:
                        raw_vcd = vf.read()
                    if raw_vcd.startswith('@xtrace'):
                        vcd_text_str = convert_xtrace_to_standard_vcd(raw_vcd)
                    else:
                        vcd_text_str = raw_vcd
                    print(f"[WTB] VCD ready: {len(vcd_text_str)} chars from {fname}")
                except Exception as e:
                    print(f"[WTB] VCD read error: {e}")
                break

    # ── Collect coverage JSON ────────────────────────────────────
    cov_data = None
    cov_path = os.path.join(tmp_dir, 'xezim_cov.json')
    if os.path.exists(cov_path):
        try:
            with open(cov_path, 'r') as cf:
                cov_data = json.load(cf)
        except Exception as e:
            print(f"[WTB] Coverage read error: {e}")

    # ── Build and return response ────────────────────────────────
    response = {
        'exit_code': result.returncode,
        'stdout':    result.stdout,
        'stderr':    result.stderr,
        'success':   result.returncode == 0,
    }
    if vcd_text_str:
        response['vcd_text'] = vcd_text_str
    if cov_data:
        response['coverage'] = cov_data

    return response
