// ─────────────────────────────────────────────────────────────────
// SurferBridge for Training Academy
// Manages the embedded Surfer WebAssembly VCD Waveform Viewer
// Docs: https://app.surfer-project.org/integration.js
// ─────────────────────────────────────────────────────────────────
(function() {
  const SAMPLE_VCD = `$version Generated by VerilatedVcd $end
$timescale 1ps $end
 $scope module top $end
  $var wire 1 - clk $end
  $var wire 1 " rst_n $end
  $var wire 3 . current_state [2:0] $end
  $var wire 32 / current_pkt [31:0] $end
  $var wire 32 # alu_a [31:0] $end
  $var wire 32 $ alu_b [31:0] $end
  $var wire 32 0 alu_out [31:0] $end
  $var wire 2 % alu_op [1:0] $end
  $scope module bus $end
   $var wire 1 - clk $end
   $var wire 1 " rst_n $end
   $var wire 1 1 valid $end
   $var wire 1 2 ready $end
   $var wire 32 3 data [31:0] $end
  $upscope $end
  $scope module u_dut $end
   $var wire 1 - clk $end
   $var wire 1 " rst_n $end
   $var wire 32 # op_a [31:0] $end
   $var wire 32 $ op_b [31:0] $end
   $var wire 2 % opcode [1:0] $end
   $var wire 32 0 result [31:0] $end
  $upscope $end
 $upscope $end
$enddefinitions $end

#0
0"
b00000000000000000000000000010000 #
b00000000000000000000000000000101 $
b00 %
0-
b000 .
b00000000000000000000000000000000 /
b00000000000000000000000000000000 0
01
02
b00000000000000000000000000000000 3
#5
1-
#10
0-
1"
#15
1-
11
b00000000000000001100101011111110 3
b001 .
#20
0-
12
#25
1-
b01 %
b00000000000000000000000000010101 0
#30
0-
01
02
b010 .
#35
1-
b10 %
#40
0-
b011 .
#45
1-
b000 .
#50
0-
#55
1-
#60
0-
$finish
`;

  window.SurferBridge = {
    _ready: false,
    _pendingVcd: null,
    _readyTimer: null,
    _loadedVcdText: null,

    get iframe() {
      return document.getElementById("surfer_iframe");
    },

    init() {
      const iframe = this.iframe;
      if (!iframe) return;

      window.addEventListener("message", (e) => {
        if (e.source !== iframe.contentWindow) return;
        const data = e.data;
        if (data && (data.type === "surfer_ready" || data === "surfer_ready")) {
          this._onReady();
        }
      });

      iframe.addEventListener("load", () => {
        if (this._readyTimer) clearTimeout(this._readyTimer);
        this._readyTimer = setTimeout(() => this._onReady(), 4000);
      });
    },

    _onReady() {
      if (this._ready) return;
      this._ready = true;
      const overlay = document.getElementById("surfer_loading_overlay");
      if (overlay) {
        overlay.style.opacity = "0";
        setTimeout(() => { overlay.style.display = "none"; }, 500);
      }
      const badge = document.getElementById("surfer_status_badge");
      if (badge) badge.textContent = "✅ Surfer ready";

      if (this._pendingVcd) {
        this._sendVcdToIframe(this._pendingVcd);
        this._pendingVcd = null;
      } else if (!this._loadedVcdText) {
        this.showNoVcdOverlay(true);
      }
    },

    loadVcd(vcdText, forceReload = false) {
      if (!vcdText) return;
      this.showNoVcdOverlay(false);
      if (!forceReload && this._loadedVcdText === vcdText) return;
      if (!this._ready) {
        this._pendingVcd = vcdText;
        return;
      }
      this._sendVcdToIframe(vcdText);
    },

    _sendVcdToIframe(vcdText) {
      const iframe = this.iframe;
      if (!iframe || !iframe.contentWindow) return;
      try {
        iframe.contentWindow.postMessage({ command: "LoadVcdData", data: vcdText }, "*");
        this._loadedVcdText = vcdText;
        const badge = document.getElementById("surfer_status_badge");
        if (badge) badge.textContent = "✅ VCD loaded in Surfer";
        this.showNoVcdOverlay(false);
      } catch (err) {
        console.warn("[SurferBridge] postMessage error:", err);
      }
    },

    loadSampleWaveform() {
      this.loadVcd(SAMPLE_VCD, true);
    },

    reloadVcd() {
      if (this._loadedVcdText) {
        this._ready = true;
        this.loadVcd(this._loadedVcdText, true);
      } else {
        this.loadSampleWaveform();
      }
    },

    toggleMenu() {
      const iframe = this.iframe;
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.postMessage({ command: "ToggleMenu" }, "*");
      }
    },

    showNoVcdOverlay(show) {
      const el = document.getElementById("surfer_novcd_overlay");
      if (el) el.style.display = show ? "flex" : "none";
    }
  };

  document.addEventListener("DOMContentLoaded", () => {
    SurferBridge.init();
  });
})();
